name: data ingestion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Data ingestion
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          chmod +x Backfill.py
          python Backfill.py

      - name: waiting for data ingestion
        run: sleep 300

      - name: Calculate MAE
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
          COMET_ML_WORKSPACE: ${{ secrets.COMET_ML_WORKSPACE }}
        run: |
          chmod +x predict.py
          python predict.py