name: predict

on:
  workflow_dispatch:

jobs:
  fetch_dogecoin_price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch Dogecoin Price
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python -c 'import requests; print(requests.get("https://api.binance.com/api/v3/ticker/price?symbol=DOGEUSDT").json())'

      - name: Display directory content
        run: ls -R